"""add news context and broker sized plans

Revision ID: 1385d072a844
Revises: 89a6d538b75a
Create Date: 2026-07-23 23:08:19.858675
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1385d072a844"
down_revision: str | Sequence[str] | None = "89a6d538b75a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_event_id", sa.String(length=160), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timing_estimated", sa.Boolean(), nullable=False),
        sa.Column("country", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=True),
        sa.Column("category", sa.String(length=160), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("actual", sa.String(length=120), nullable=True),
        sa.Column("forecast", sa.String(length=120), nullable=True),
        sa.Column("previous", sa.String(length=120), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.CheckConstraint("importance BETWEEN 0 AND 3", name="ck_economic_event_importance"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_event_id", name="uq_economic_event_source"),
    )
    op.create_index(
        op.f("ix_economic_events_country"), "economic_events", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_economic_events_currency"), "economic_events", ["currency"], unique=False
    )
    op.create_index(
        op.f("ix_economic_events_importance"), "economic_events", ["importance"], unique=False
    )
    op.create_index(
        op.f("ix_economic_events_retrieved_at"), "economic_events", ["retrieved_at"], unique=False
    )
    op.create_index(
        op.f("ix_economic_events_scheduled_at"), "economic_events", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_economic_events_source"), "economic_events", ["source"], unique=False)
    op.create_table(
        "news_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_item_id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=160), nullable=True),
        sa.Column("symbol", sa.String(length=120), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint("importance BETWEEN 0 AND 3", name="ck_news_item_importance"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_item_id", name="uq_news_item_source"),
    )
    op.create_index(op.f("ix_news_items_category"), "news_items", ["category"], unique=False)
    op.create_index(op.f("ix_news_items_country"), "news_items", ["country"], unique=False)
    op.create_index(
        op.f("ix_news_items_published_at"), "news_items", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_news_items_source"), "news_items", ["source"], unique=False)
    op.create_index(op.f("ix_news_items_symbol"), "news_items", ["symbol"], unique=False)
    op.add_column("trade_plans", sa.Column("instrument_specification_id", sa.UUID(), nullable=True))
    op.add_column("trade_plans", sa.Column("session_name", sa.String(length=40), nullable=True))
    op.add_column(
        "trade_plans",
        sa.Column("estimated_costs", sa.Numeric(precision=24, scale=4), nullable=True),
    )
    op.add_column(
        "trade_plans",
        sa.Column("estimated_margin", sa.Numeric(precision=24, scale=4), nullable=True),
    )
    op.add_column(
        "trade_plans", sa.Column("minutes_to_high_impact_event", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_trade_plans_instrument_specification_id"),
        "trade_plans",
        ["instrument_specification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trade_plans_session_name"), "trade_plans", ["session_name"], unique=False
    )
    op.create_foreign_key(
        None, "trade_plans", "instrument_specifications", ["instrument_specification_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trade_plans", type_="foreignkey")
    op.drop_index(op.f("ix_trade_plans_session_name"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_instrument_specification_id"), table_name="trade_plans")
    op.drop_column("trade_plans", "minutes_to_high_impact_event")
    op.drop_column("trade_plans", "estimated_margin")
    op.drop_column("trade_plans", "estimated_costs")
    op.drop_column("trade_plans", "session_name")
    op.drop_column("trade_plans", "instrument_specification_id")
    op.drop_index(op.f("ix_news_items_symbol"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_source"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_published_at"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_country"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_category"), table_name="news_items")
    op.drop_table("news_items")
    op.drop_index(op.f("ix_economic_events_source"), table_name="economic_events")
    op.drop_index(op.f("ix_economic_events_scheduled_at"), table_name="economic_events")
    op.drop_index(op.f("ix_economic_events_retrieved_at"), table_name="economic_events")
    op.drop_index(op.f("ix_economic_events_importance"), table_name="economic_events")
    op.drop_index(op.f("ix_economic_events_currency"), table_name="economic_events")
    op.drop_index(op.f("ix_economic_events_country"), table_name="economic_events")
    op.drop_table("economic_events")
    # ### end Alembic commands ###
