"""add broker specifications and analysis provenance

Revision ID: 89a6d538b75a
Revises: 9c3c7ba19382
Create Date: 2026-07-23 23:01:50.344422
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "89a6d538b75a"
down_revision: str | Sequence[str] | None = "9c3c7ba19382"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instrument_specifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instrument_mapping_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("contract_size", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column(
            "tick_value_per_quantity_unit", sa.Numeric(precision=24, scale=4), nullable=False
        ),
        sa.Column("minimum_quantity", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("maximum_quantity", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("quantity_step", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("margin_rate", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("estimated_spread", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("commission_per_quantity", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("financing_per_quantity_day", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("pnl_currency", sa.String(length=12), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("contract_size > 0", name="ck_instrument_spec_contract_size"),
        sa.CheckConstraint(
            "margin_rate IS NULL OR (margin_rate > 0 AND margin_rate <= 1)",
            name="ck_instrument_spec_margin",
        ),
        sa.CheckConstraint(
            "maximum_quantity >= minimum_quantity", name="ck_instrument_spec_maximum"
        ),
        sa.CheckConstraint("minimum_quantity > 0", name="ck_instrument_spec_minimum"),
        sa.CheckConstraint("quantity_step > 0", name="ck_instrument_spec_step"),
        sa.CheckConstraint("tick_size > 0", name="ck_instrument_spec_tick_size"),
        sa.CheckConstraint(
            "tick_value_per_quantity_unit > 0", name="ck_instrument_spec_tick_value"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_mapping_id"], ["instrument_mappings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument_mapping_id", "effective_from", name="uq_instrument_specification_effective"
        ),
    )
    op.create_index(
        op.f("ix_instrument_specifications_account_id"),
        "instrument_specifications",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_specifications_effective_from"),
        "instrument_specifications",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_specifications_instrument_mapping_id"),
        "instrument_specifications",
        ["instrument_mapping_id"],
        unique=False,
    )
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=True),
        sa.Column("trade_plan_id", sa.UUID(), nullable=True),
        sa.Column("analysis_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("output_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_type", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "analysis_type IN ('chart', 'news', 'market', 'review')", name="ck_analysis_run_type"
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'failed', 'corrected')", name="ck_analysis_run_status"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_plan_id"],
            ["trade_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_runs_analysis_type"), "analysis_runs", ["analysis_type"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_runs_created_at"), "analysis_runs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_runs_evidence_id"), "analysis_runs", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_runs_trade_plan_id"), "analysis_runs", ["trade_plan_id"], unique=False
    )
    op.create_unique_constraint("uq_order_approval_intent", "order_approvals", ["order_intent_id"])
    op.add_column(
        "trade_reflections",
        sa.Column("process_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "trade_reflections",
        sa.Column("outcome_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "trade_reflections",
        sa.Column(
            "maximum_favorable_excursion_r", sa.Numeric(precision=12, scale=4), nullable=True
        ),
    )
    op.add_column(
        "trade_reflections",
        sa.Column("maximum_adverse_excursion_r", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "trade_reflections",
        sa.Column("total_fees", sa.Numeric(precision=24, scale=4), nullable=True),
    )
    op.add_column(
        "trade_reflections",
        sa.Column("slippage_cost", sa.Numeric(precision=24, scale=4), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trade_reflections", "slippage_cost")
    op.drop_column("trade_reflections", "total_fees")
    op.drop_column("trade_reflections", "maximum_adverse_excursion_r")
    op.drop_column("trade_reflections", "maximum_favorable_excursion_r")
    op.drop_column("trade_reflections", "outcome_score")
    op.drop_column("trade_reflections", "process_score")
    op.drop_constraint("uq_order_approval_intent", "order_approvals", type_="unique")
    op.drop_index(op.f("ix_analysis_runs_trade_plan_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_evidence_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_created_at"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_analysis_type"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_index(
        op.f("ix_instrument_specifications_instrument_mapping_id"),
        table_name="instrument_specifications",
    )
    op.drop_index(
        op.f("ix_instrument_specifications_effective_from"), table_name="instrument_specifications"
    )
    op.drop_index(
        op.f("ix_instrument_specifications_account_id"), table_name="instrument_specifications"
    )
    op.drop_table("instrument_specifications")
    # ### end Alembic commands ###
