"""record trade management decisions

Revision ID: 9c3c7ba19382
Revises: cd31dfdbeb95
Create Date: 2026-07-23 22:31:44.164702
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c3c7ba19382"
down_revision: str | Sequence[str] | None = "cd31dfdbeb95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_management_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("order_intent_id", sa.UUID(), nullable=True),
        sa.Column("execution_event_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("quantity_delta", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("position_quantity_after", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("realized_r_at_event", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('human', 'agent', 'import', 'system')", name="ck_trade_management_actor"
        ),
        sa.CheckConstraint(
            "event_type IN ("
            "'partial_taken', 'stop_moved', 'target_moved', 'breakeven_set', "
            "'runner_left', 'hedge_considered', 'hedge_taken', 'manual_close', 'note'"
            ")",
            name="ck_trade_management_event_type",
        ),
        sa.ForeignKeyConstraint(
            ["execution_event_id"],
            ["execution_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id"],
            ["order_intents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trade_management_events_event_type"),
        "trade_management_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trade_management_events_execution_event_id"),
        "trade_management_events",
        ["execution_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trade_management_events_occurred_at"),
        "trade_management_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trade_management_events_order_intent_id"),
        "trade_management_events",
        ["order_intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trade_management_events_trade_id"),
        "trade_management_events",
        ["trade_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_management_events_trade_id"), table_name="trade_management_events")
    op.drop_index(
        op.f("ix_trade_management_events_order_intent_id"), table_name="trade_management_events"
    )
    op.drop_index(
        op.f("ix_trade_management_events_occurred_at"), table_name="trade_management_events"
    )
    op.drop_index(
        op.f("ix_trade_management_events_execution_event_id"), table_name="trade_management_events"
    )
    op.drop_index(
        op.f("ix_trade_management_events_event_type"), table_name="trade_management_events"
    )
    op.drop_table("trade_management_events")
    # ### end Alembic commands ###
