"""execution centered trading schema

Revision ID: cd31dfdbeb95
Revises:
Create Date: 2026-07-23 22:25:58.300356
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cd31dfdbeb95"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_sessions_created_at"),
        "conversation_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_sessions_name"), "conversation_sessions", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_conversation_sessions_updated_at"),
        "conversation_sessions",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_symbol", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=True),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("base_currency", sa.String(length=12), nullable=True),
        sa.Column("quote_currency", sa.String(length=12), nullable=True),
        sa.Column("price_precision", sa.Integer(), nullable=False),
        sa.Column("quantity_precision", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price_precision >= 0", name="ck_instrument_price_precision"),
        sa.CheckConstraint("quantity_precision >= 0", name="ck_instrument_quantity_precision"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_symbol", "asset_class", name="uq_instrument_identity"),
    )
    op.create_index(
        op.f("ix_instruments_asset_class"), "instruments", ["asset_class"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_canonical_symbol"), "instruments", ["canonical_symbol"], unique=False
    )
    op.create_table(
        "playbooks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playbooks_name"), "playbooks", ["name"], unique=True)
    op.create_table(
        "trading_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("broker", sa.String(length=40), nullable=False),
        sa.Column("external_account_id", sa.String(length=160), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('practice', 'live', 'backtest')", name="ck_account_mode"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker", "external_account_id", name="uq_trading_account_external"),
    )
    op.create_index(
        op.f("ix_trading_accounts_broker"), "trading_accounts", ["broker"], unique=False
    )
    op.create_table(
        "broker_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "config_reference",
            sa.String(length=255),
            nullable=True,
            comment="Secret-store reference only; never the credential itself.",
        ),
        sa.Column("last_healthy_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('configured', 'healthy', 'degraded', 'disabled')",
            name="ck_broker_connection_status",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["trading_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "account_id", name="uq_broker_connection_account"),
    )
    op.create_index(
        op.f("ix_broker_connections_account_id"), "broker_connections", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_broker_connections_provider"), "broker_connections", ["provider"], unique=False
    )
    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name="ck_turn_role"),
        sa.ForeignKeyConstraint(["session_id"], ["conversation_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_turns_created_at"), "conversation_turns", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_turns_session_id"), "conversation_turns", ["session_id"], unique=False
    )
    op.create_table(
        "instrument_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_symbol", sa.String(length=80), nullable=False),
        sa.Column("venue", sa.String(length=80), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_symbol", name="uq_instrument_mapping_external"),
    )
    op.create_index(
        op.f("ix_instrument_mappings_external_symbol"),
        "instrument_mappings",
        ["external_symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_mappings_instrument_id"),
        "instrument_mappings",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_mappings_provider"), "instrument_mappings", ["provider"], unique=False
    )
    op.create_table(
        "playbook_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("playbook_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_hypothesis", sa.Text(), nullable=True),
        sa.Column("sample_requirement", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="ck_playbook_version_positive"),
        sa.ForeignKeyConstraint(["playbook_id"], ["playbooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playbook_id", "version", name="uq_playbook_version"),
    )
    op.create_index(
        op.f("ix_playbook_versions_playbook_id"), "playbook_versions", ["playbook_id"], unique=False
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("external_trade_id", sa.String(length=160), nullable=True),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("direction IN ('long', 'short')", name="ck_trade_direction"),
        sa.CheckConstraint(
            "status IN ('planned', 'open', 'partially_closed', 'closed', 'cancelled')",
            name="ck_trade_status",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "external_trade_id", name="uq_trade_external"),
    )
    op.create_index(op.f("ix_trades_account_id"), "trades", ["account_id"], unique=False)
    op.create_index(op.f("ix_trades_closed_at"), "trades", ["closed_at"], unique=False)
    op.create_index(op.f("ix_trades_created_at"), "trades", ["created_at"], unique=False)
    op.create_index(op.f("ix_trades_instrument_id"), "trades", ["instrument_id"], unique=False)
    op.create_index(op.f("ix_trades_opened_at"), "trades", ["opened_at"], unique=False)
    op.create_index(op.f("ix_trades_status"), "trades", ["status"], unique=False)
    op.create_table(
        "connector_cursors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("stream_name", sa.String(length=80), nullable=False),
        sa.Column("cursor_value", sa.String(length=255), nullable=False),
        sa.Column("source_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connection_id"], ["broker_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "stream_name", name="uq_connector_cursor_stream"),
    )
    op.create_index(
        op.f("ix_connector_cursors_connection_id"),
        "connector_cursors",
        ["connection_id"],
        unique=False,
    )
    op.create_table(
        "position_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("trigger", sa.String(length=24), nullable=False),
        sa.Column("net_quantity", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("unrealized_pnl", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("market_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "trigger IN ('fill', 'management', 'review', 'manual', 'reconciliation')",
            name="ck_position_snapshot_trigger",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_position_snapshots_account_id"), "position_snapshots", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_position_snapshots_instrument_id"),
        "position_snapshots",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_position_snapshots_market_time"),
        "position_snapshots",
        ["market_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_position_snapshots_trade_id"), "position_snapshots", ["trade_id"], unique=False
    )
    op.create_table(
        "trade_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("instrument_id", sa.UUID(), nullable=True),
        sa.Column("playbook_version_id", sa.UUID(), nullable=True),
        sa.Column("instrument", sa.String(length=32), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=True),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("setup_name", sa.String(length=120), nullable=False),
        sa.Column("regime", sa.String(length=64), nullable=True),
        sa.Column("context_timeframe", sa.String(length=16), nullable=False),
        sa.Column("trigger_timeframe", sa.String(length=16), nullable=False),
        sa.Column("entry", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("stop", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("target", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("account_equity", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("risk_percent", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("value_per_price_unit", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("risk_amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("planned_r", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("invalidation", sa.Text(), nullable=False),
        sa.Column("observations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("interpretations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("policy_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("direction IN ('long', 'short')", name="ck_trade_plan_direction"),
        sa.CheckConstraint(
            "status IN ('draft', 'planned', 'invalidated', 'executed', 'reviewed')",
            name="ck_trade_plan_status",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_trade_plan_quantity"),
        sa.CheckConstraint("risk_amount > 0", name="ck_trade_plan_risk_amount"),
        sa.CheckConstraint("risk_percent > 0", name="ck_trade_plan_risk_percent"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_version_id"],
            ["playbook_versions.id"],
        ),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trade_plans_account_id"), "trade_plans", ["account_id"], unique=False)
    op.create_index(op.f("ix_trade_plans_created_at"), "trade_plans", ["created_at"], unique=False)
    op.create_index(op.f("ix_trade_plans_instrument"), "trade_plans", ["instrument"], unique=False)
    op.create_index(
        op.f("ix_trade_plans_instrument_id"), "trade_plans", ["instrument_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_plans_playbook_version_id"),
        "trade_plans",
        ["playbook_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_trade_plans_regime"), "trade_plans", ["regime"], unique=False)
    op.create_index(op.f("ix_trade_plans_setup_name"), "trade_plans", ["setup_name"], unique=False)
    op.create_index(op.f("ix_trade_plans_status"), "trade_plans", ["status"], unique=False)
    op.create_index(op.f("ix_trade_plans_trade_id"), "trade_plans", ["trade_id"], unique=False)
    op.create_table(
        "market_contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("trade_plan_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("venue", sa.String(length=80), nullable=False),
        sa.Column("timeframe", sa.String(length=16), nullable=False),
        sa.Column("market_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hypotheses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_plan_id"],
            ["trade_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source",
            "instrument_id",
            "timeframe",
            "market_time",
            name="uq_market_context_observation",
        ),
    )
    op.create_index(
        op.f("ix_market_contexts_instrument_id"), "market_contexts", ["instrument_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_contexts_market_time"), "market_contexts", ["market_time"], unique=False
    )
    op.create_index(op.f("ix_market_contexts_source"), "market_contexts", ["source"], unique=False)
    op.create_index(
        op.f("ix_market_contexts_timeframe"), "market_contexts", ["timeframe"], unique=False
    )
    op.create_index(
        op.f("ix_market_contexts_trade_plan_id"), "market_contexts", ["trade_plan_id"], unique=False
    )
    op.create_table(
        "mindset_checkins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_plan_id", sa.UUID(), nullable=True),
        sa.Column("phase", sa.String(length=24), nullable=False),
        sa.Column("readiness", sa.Integer(), nullable=False),
        sa.Column("accepted_risk", sa.Boolean(), nullable=False),
        sa.Column("emotion_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "phase IN ('pre_session', 'pre_trade', 'during_trade', 'post_trade')",
            name="ck_mindset_phase",
        ),
        sa.CheckConstraint("readiness BETWEEN 1 AND 5", name="ck_mindset_readiness"),
        sa.ForeignKeyConstraint(
            ["trade_plan_id"],
            ["trade_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mindset_checkins_created_at"), "mindset_checkins", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_mindset_checkins_trade_plan_id"),
        "mindset_checkins",
        ["trade_plan_id"],
        unique=False,
    )
    op.create_table(
        "order_intents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("trade_plan_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("target_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("time_in_force", sa.String(length=16), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("proposed_by", sa.String(length=24), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('open', 'reduce', 'close', 'modify_stop', 'modify_target', 'hedge')",
            name="ck_order_intent_action",
        ),
        sa.CheckConstraint("side IN ('buy', 'sell')", name="ck_order_intent_side"),
        sa.CheckConstraint(
            "status IN ('proposed', 'approved', 'rejected', 'expired', 'submitted', 'failed')",
            name="ck_order_intent_status",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_order_intent_quantity"),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_plan_id"],
            ["trade_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_order_intent_idempotency"),
    )
    op.create_index(
        op.f("ix_order_intents_created_at"), "order_intents", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_order_intents_status"), "order_intents", ["status"], unique=False)
    op.create_index(op.f("ix_order_intents_trade_id"), "order_intents", ["trade_id"], unique=False)
    op.create_index(
        op.f("ix_order_intents_trade_plan_id"), "order_intents", ["trade_plan_id"], unique=False
    )
    op.create_table(
        "trade_reflections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("lifecycle_trade_id", sa.UUID(), nullable=True),
        sa.Column("exit_average", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("realized_r", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("execution_grade", sa.String(length=8), nullable=False),
        sa.Column("outcome_grade", sa.String(length=16), nullable=True),
        sa.Column("rule_adherence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("emotion_before", sa.Text(), nullable=True),
        sa.Column("emotion_during", sa.Text(), nullable=True),
        sa.Column("emotion_after", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("execution_grade IN ('A', 'B', 'C', 'D', 'F')", name="ck_review_grade"),
        sa.ForeignKeyConstraint(
            ["lifecycle_trade_id"],
            ["trades.id"],
        ),
        sa.ForeignKeyConstraint(["trade_id"], ["trade_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trade_id"),
    )
    op.create_index(
        op.f("ix_trade_reflections_lifecycle_trade_id"),
        "trade_reflections",
        ["lifecycle_trade_id"],
        unique=False,
    )
    op.create_table(
        "evidence_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("trade_plan_id", sa.UUID(), nullable=True),
        sa.Column("market_context_id", sa.UUID(), nullable=True),
        sa.Column("evidence_type", sa.String(length=24), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("market_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "evidence_type IN ('chart', 'news', 'calendar', 'note', 'broker_record')",
            name="ck_evidence_type",
        ),
        sa.ForeignKeyConstraint(
            ["market_context_id"],
            ["market_contexts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_plan_id"],
            ["trade_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", "storage_uri", name="uq_evidence_content_location"),
    )
    op.create_index(
        op.f("ix_evidence_items_market_context_id"),
        "evidence_items",
        ["market_context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_trade_id"), "evidence_items", ["trade_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_trade_plan_id"), "evidence_items", ["trade_plan_id"], unique=False
    )
    op.create_table(
        "execution_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("order_intent_id", sa.UUID(), nullable=True),
        sa.Column("external_event_id", sa.String(length=160), nullable=False),
        sa.Column("external_order_id", sa.String(length=160), nullable=True),
        sa.Column("external_trade_id", sa.String(length=160), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_payload_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Sanitized metadata only; no credentials or full payload.",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["broker_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id"],
            ["order_intents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id", "external_event_id", name="uq_execution_event_external"
        ),
    )
    op.create_index(
        op.f("ix_execution_events_connection_id"),
        "execution_events",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_event_type"), "execution_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_external_order_id"),
        "execution_events",
        ["external_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_external_trade_id"),
        "execution_events",
        ["external_trade_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_ingested_at"), "execution_events", ["ingested_at"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_occurred_at"), "execution_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_order_intent_id"),
        "execution_events",
        ["order_intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_trade_id"), "execution_events", ["trade_id"], unique=False
    )
    op.create_table(
        "order_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_intent_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("intent_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')", name="ck_order_approval_decision"
        ),
        sa.ForeignKeyConstraint(["order_intent_id"], ["order_intents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_approvals_order_intent_id"),
        "order_approvals",
        ["order_intent_id"],
        unique=False,
    )
    op.create_table(
        "rule_evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reflection_id", sa.UUID(), nullable=False),
        sa.Column("playbook_version_id", sa.UUID(), nullable=True),
        sa.Column("rule_key", sa.String(length=120), nullable=False),
        sa.Column("result", sa.String(length=24), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "result IN ('met', 'not_met', 'unclear', 'not_applicable')",
            name="ck_rule_evaluation_result",
        ),
        sa.ForeignKeyConstraint(
            ["playbook_version_id"],
            ["playbook_versions.id"],
        ),
        sa.ForeignKeyConstraint(["reflection_id"], ["trade_reflections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rule_evaluations_playbook_version_id"),
        "rule_evaluations",
        ["playbook_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rule_evaluations_reflection_id"),
        "rule_evaluations",
        ["reflection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rule_evaluations_rule_key"), "rule_evaluations", ["rule_key"], unique=False
    )
    op.create_table(
        "account_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("execution_event_id", sa.UUID(), nullable=True),
        sa.Column("trigger", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("balance", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("equity", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("margin_used", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("margin_available", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("market_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "trigger IN ('fill', 'management', 'review', 'manual', 'reconciliation')",
            name="ck_account_snapshot_trigger",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_event_id"],
            ["execution_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_snapshots_account_id"), "account_snapshots", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_account_snapshots_execution_event_id"),
        "account_snapshots",
        ["execution_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_snapshots_market_time"), "account_snapshots", ["market_time"], unique=False
    )
    op.create_table(
        "fills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("execution_event_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("external_fill_id", sa.String(length=160), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("commission", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("financing", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("side IN ('buy', 'sell')", name="ck_fill_side"),
        sa.CheckConstraint("quantity > 0", name="ck_fill_quantity"),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["broker_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_event_id"],
            ["execution_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "external_fill_id", name="uq_fill_external"),
    )
    op.create_index(op.f("ix_fills_connection_id"), "fills", ["connection_id"], unique=False)
    op.create_index(
        op.f("ix_fills_execution_event_id"), "fills", ["execution_event_id"], unique=False
    )
    op.create_index(op.f("ix_fills_instrument_id"), "fills", ["instrument_id"], unique=False)
    op.create_index(op.f("ix_fills_occurred_at"), "fills", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_fills_trade_id"), "fills", ["trade_id"], unique=False)
    op.create_table(
        "observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_plan_id", sa.UUID(), nullable=True),
        sa.Column("market_context_id", sa.UUID(), nullable=True),
        sa.Column("evidence_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('human', 'agent', 'import', 'system')", name="ck_observation_actor"
        ),
        sa.CheckConstraint(
            "kind IN ('fact', 'hypothesis', 'question', 'confirmation')", name="ck_observation_kind"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_context_id"],
            ["market_contexts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_plan_id"],
            ["trade_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observations_evidence_id"), "observations", ["evidence_id"], unique=False
    )
    op.create_index(op.f("ix_observations_kind"), "observations", ["kind"], unique=False)
    op.create_index(
        op.f("ix_observations_market_context_id"),
        "observations",
        ["market_context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observations_trade_plan_id"), "observations", ["trade_plan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observations_trade_plan_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_market_context_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_kind"), table_name="observations")
    op.drop_index(op.f("ix_observations_evidence_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_fills_trade_id"), table_name="fills")
    op.drop_index(op.f("ix_fills_occurred_at"), table_name="fills")
    op.drop_index(op.f("ix_fills_instrument_id"), table_name="fills")
    op.drop_index(op.f("ix_fills_execution_event_id"), table_name="fills")
    op.drop_index(op.f("ix_fills_connection_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_account_snapshots_market_time"), table_name="account_snapshots")
    op.drop_index(op.f("ix_account_snapshots_execution_event_id"), table_name="account_snapshots")
    op.drop_index(op.f("ix_account_snapshots_account_id"), table_name="account_snapshots")
    op.drop_table("account_snapshots")
    op.drop_index(op.f("ix_rule_evaluations_rule_key"), table_name="rule_evaluations")
    op.drop_index(op.f("ix_rule_evaluations_reflection_id"), table_name="rule_evaluations")
    op.drop_index(op.f("ix_rule_evaluations_playbook_version_id"), table_name="rule_evaluations")
    op.drop_table("rule_evaluations")
    op.drop_index(op.f("ix_order_approvals_order_intent_id"), table_name="order_approvals")
    op.drop_table("order_approvals")
    op.drop_index(op.f("ix_execution_events_trade_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_order_intent_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_occurred_at"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_ingested_at"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_external_trade_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_external_order_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_event_type"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_connection_id"), table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index(op.f("ix_evidence_items_trade_plan_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_trade_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_market_context_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_trade_reflections_lifecycle_trade_id"), table_name="trade_reflections")
    op.drop_table("trade_reflections")
    op.drop_index(op.f("ix_order_intents_trade_plan_id"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_trade_id"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_status"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_created_at"), table_name="order_intents")
    op.drop_table("order_intents")
    op.drop_index(op.f("ix_mindset_checkins_trade_plan_id"), table_name="mindset_checkins")
    op.drop_index(op.f("ix_mindset_checkins_created_at"), table_name="mindset_checkins")
    op.drop_table("mindset_checkins")
    op.drop_index(op.f("ix_market_contexts_trade_plan_id"), table_name="market_contexts")
    op.drop_index(op.f("ix_market_contexts_timeframe"), table_name="market_contexts")
    op.drop_index(op.f("ix_market_contexts_source"), table_name="market_contexts")
    op.drop_index(op.f("ix_market_contexts_market_time"), table_name="market_contexts")
    op.drop_index(op.f("ix_market_contexts_instrument_id"), table_name="market_contexts")
    op.drop_table("market_contexts")
    op.drop_index(op.f("ix_trade_plans_trade_id"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_status"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_setup_name"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_regime"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_playbook_version_id"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_instrument_id"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_instrument"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_created_at"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_account_id"), table_name="trade_plans")
    op.drop_table("trade_plans")
    op.drop_index(op.f("ix_position_snapshots_trade_id"), table_name="position_snapshots")
    op.drop_index(op.f("ix_position_snapshots_market_time"), table_name="position_snapshots")
    op.drop_index(op.f("ix_position_snapshots_instrument_id"), table_name="position_snapshots")
    op.drop_index(op.f("ix_position_snapshots_account_id"), table_name="position_snapshots")
    op.drop_table("position_snapshots")
    op.drop_index(op.f("ix_connector_cursors_connection_id"), table_name="connector_cursors")
    op.drop_table("connector_cursors")
    op.drop_index(op.f("ix_trades_status"), table_name="trades")
    op.drop_index(op.f("ix_trades_opened_at"), table_name="trades")
    op.drop_index(op.f("ix_trades_instrument_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_created_at"), table_name="trades")
    op.drop_index(op.f("ix_trades_closed_at"), table_name="trades")
    op.drop_index(op.f("ix_trades_account_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_playbook_versions_playbook_id"), table_name="playbook_versions")
    op.drop_table("playbook_versions")
    op.drop_index(op.f("ix_instrument_mappings_provider"), table_name="instrument_mappings")
    op.drop_index(op.f("ix_instrument_mappings_instrument_id"), table_name="instrument_mappings")
    op.drop_index(op.f("ix_instrument_mappings_external_symbol"), table_name="instrument_mappings")
    op.drop_table("instrument_mappings")
    op.drop_index(op.f("ix_conversation_turns_session_id"), table_name="conversation_turns")
    op.drop_index(op.f("ix_conversation_turns_created_at"), table_name="conversation_turns")
    op.drop_table("conversation_turns")
    op.drop_index(op.f("ix_broker_connections_provider"), table_name="broker_connections")
    op.drop_index(op.f("ix_broker_connections_account_id"), table_name="broker_connections")
    op.drop_table("broker_connections")
    op.drop_index(op.f("ix_trading_accounts_broker"), table_name="trading_accounts")
    op.drop_table("trading_accounts")
    op.drop_index(op.f("ix_playbooks_name"), table_name="playbooks")
    op.drop_table("playbooks")
    op.drop_index(op.f("ix_instruments_canonical_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_asset_class"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_conversation_sessions_updated_at"), table_name="conversation_sessions")
    op.drop_index(op.f("ix_conversation_sessions_name"), table_name="conversation_sessions")
    op.drop_index(op.f("ix_conversation_sessions_created_at"), table_name="conversation_sessions")
    op.drop_table("conversation_sessions")
    # ### end Alembic commands ###
