import math
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Literal
from urllib.parse import urlparse

import httpx
from sqlalchemy import Engine

from app.config import Settings
from app.system_resources import GIB, assess_model_download, resource_snapshot

ProviderName = Literal["openai", "anthropic", "ollama"]
OllamaTier = Literal["default", "economy", "balanced", "deep", "quality", "all"]
OLLAMA_MODEL_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._/:+-]{0,199}")
OLLAMA_PARAMETER_COUNT = re.compile(r"(?<![0-9])([0-9]+(?:\.[0-9]+)?)b(?:\b|-)", re.I)
WINDOWS_LAUNCHER_MARKER = ":: Generated by Trading Agent setup"

SAFE_SETUP_KEYS = frozenset(
    {
        "MODEL_PROVIDER",
        "OLLAMA_BASE_URL",
        "OLLAMA_MODEL",
        "OLLAMA_ECONOMY_MODEL",
        "OLLAMA_BALANCED_MODEL",
        "OLLAMA_DEEP_MODEL",
        "OLLAMA_CONTEXT_LENGTH",
        "STARTUP_MODEL_SMOKE_TEST",
        "LOCAL_SERVICE_AUTOSTART",
        "POSTGRES_SERVICE_NAME",
        "DATABASE_MODE",
        "TRADING_WORKSPACE",
        "TRADING_ACCOUNT",
        "MAXIMUM_TRADE_RISK_PERCENT",
        "BROKER_PROVIDER",
        "METATRADER_PLATFORM",
        "NEWS_PROVIDER",
        "TRADINGVIEW_WEBHOOK_ENABLED",
    }
)


def update_env_file(path: Path, values: dict[str, str]) -> None:
    unknown = set(values) - SAFE_SETUP_KEYS
    if unknown:
        raise ValueError(f"setup cannot write unsupported settings: {sorted(unknown)}")
    if any(any(character in value for character in "\r\n\0") for value in values.values()):
        raise ValueError("setup values cannot contain control characters")

    if path.is_symlink():
        raise ValueError("setup refuses to read or replace a symlinked environment file")
    existing = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    pending = dict(values)
    output: list[str] = []
    written: set[str] = set()
    for line in existing:
        key, separator, _ = line.partition("=")
        if separator and key in pending:
            if key not in written:
                output.append(f"{key}={pending[key]}")
                written.add(key)
            continue
        output.append(line)
    for key, value in pending.items():
        if key not in written:
            output.append(f"{key}={value}")

    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write("\n".join(output).rstrip() + "\n")
        temporary.chmod(0o600)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)
    path.chmod(0o600)


def snapshot_env_file(path: Path) -> bytes | None:
    """Capture a private env file so a coordinated database write can be undone."""
    if path.is_symlink():
        raise ValueError("setup refuses to read or replace a symlinked environment file")
    return path.read_bytes() if path.exists() else None


def restore_env_file(path: Path, snapshot: bytes | None) -> None:
    """Restore an env snapshot atomically after a related database failure."""
    if path.is_symlink():
        raise ValueError("setup refuses to read or replace a symlinked environment file")
    if snapshot is None:
        path.unlink(missing_ok=True)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".restore",
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(snapshot)
        temporary.chmod(0o600)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)
    path.chmod(0o600)


def provider_settings(provider: ProviderName, model: str = "qwen3.5:9b") -> dict[str, str]:
    if not OLLAMA_MODEL_PATTERN.fullmatch(model):
        raise ValueError("Ollama model name contains unsupported characters")
    values = {"MODEL_PROVIDER": provider}
    if provider == "ollama":
        values.update(
            {
                "OLLAMA_BASE_URL": "http://127.0.0.1:11434",
                "OLLAMA_MODEL": model,
                "OLLAMA_ECONOMY_MODEL": model,
                "OLLAMA_BALANCED_MODEL": model,
                "OLLAMA_DEEP_MODEL": model,
                "OLLAMA_CONTEXT_LENGTH": "16384",
                "STARTUP_MODEL_SMOKE_TEST": "true",
                "LOCAL_SERVICE_AUTOSTART": "true",
            }
        )
    return values


def ollama_profile_settings(model: str, tier: OllamaTier) -> dict[str, str]:
    if not OLLAMA_MODEL_PATTERN.fullmatch(model):
        raise ValueError("Ollama model name contains unsupported characters")
    keys = {
        "default": ("OLLAMA_MODEL",),
        "economy": ("OLLAMA_ECONOMY_MODEL",),
        "balanced": ("OLLAMA_BALANCED_MODEL",),
        "deep": ("OLLAMA_DEEP_MODEL",),
        "quality": ("OLLAMA_BALANCED_MODEL", "OLLAMA_DEEP_MODEL"),
        "all": (
            "OLLAMA_MODEL",
            "OLLAMA_ECONOMY_MODEL",
            "OLLAMA_BALANCED_MODEL",
            "OLLAMA_DEEP_MODEL",
        ),
    }
    return {key: model for key in keys[tier]}


def operating_system() -> Literal["macos", "linux", "windows", "other"]:
    system = platform.system().lower()
    if system == "darwin":
        return "macos"
    if system == "linux":
        return "linux"
    if system == "windows":
        return "windows"
    return "other"


def launcher_target_for_interpreter(
    interpreter: Path,
    *,
    system: str | None = None,
) -> Path:
    resolved_system = system or operating_system()
    executable = "trade.exe" if resolved_system == "windows" else "trade"
    return interpreter.parent / executable


def install_user_launcher(
    target: Path,
    launcher_name: str = "trade",
    *,
    system: str | None = None,
) -> Path:
    if not target.is_file():
        raise FileNotFoundError(
            f"launcher target is not a regular file: {target}"
        )
    resolved_system = system or operating_system()
    if resolved_system == "windows":
        local_app_data = os.environ.get("LOCALAPPDATA")
        base = Path(local_app_data) if local_app_data else Path.home() / "AppData" / "Local"
        bin_directory = base / "TradingAgent" / "bin"
        bin_directory.mkdir(parents=True, exist_ok=True)
        launcher = bin_directory / f"{launcher_name}.cmd"
        if launcher.is_symlink():
            raise FileExistsError(f"refusing to replace existing symlink: {launcher}")
        if launcher.exists():
            existing = launcher.read_text(encoding="utf-8")
            if not existing.startswith(WINDOWS_LAUNCHER_MARKER):
                raise FileExistsError(f"refusing to replace existing file: {launcher}")
        escaped_target = str(target.resolve()).replace("%", "%%")
        descriptor, temporary_name = tempfile.mkstemp(
            dir=bin_directory,
            prefix=f".{launcher.name}.",
            suffix=".tmp",
        )
        temporary = Path(temporary_name)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as handle:
                handle.write(
                    f'{WINDOWS_LAUNCHER_MARKER}\r\n'
                    f'@echo off\r\n"{escaped_target}" %*\r\n'
                )
            temporary.replace(launcher)
        finally:
            temporary.unlink(missing_ok=True)
        return launcher

    bin_directory = Path.home() / ".local" / "bin"
    bin_directory.mkdir(parents=True, exist_ok=True)
    launcher = bin_directory / launcher_name
    if launcher.exists() and not launcher.is_symlink():
        raise FileExistsError(f"refusing to replace existing file: {launcher}")
    if launcher.is_symlink():
        launcher.unlink()
    launcher.symlink_to(target.resolve())
    return launcher


def _homebrew() -> str | None:
    return shutil.which("brew")


def start_homebrew_service(service_name: str) -> tuple[bool, str]:
    brew = _homebrew()
    if brew is None:
        return False, "Homebrew is not installed"
    result = subprocess.run(  # noqa: S603
        [brew, "services", "start", service_name],
        check=False,
        capture_output=True,
        text=True,
        timeout=120,
    )
    detail = (result.stdout or result.stderr).strip()
    return result.returncode == 0, detail[:500]


def dependency_guidance(dependency: Literal["ollama", "postgresql"]) -> str:
    system = operating_system()
    guidance = {
        ("macos", "ollama"): (
            "Install Ollama from https://ollama.com/download/mac or with "
            "`brew install ollama`."
        ),
        ("linux", "ollama"): (
            "Install Ollama using the Linux instructions at "
            "https://ollama.com/download/linux, then start `ollama serve`."
        ),
        ("windows", "ollama"): (
            "Install and launch Ollama for Windows from "
            "https://ollama.com/download/windows."
        ),
        ("macos", "postgresql"): (
            "Run PostgreSQL with `docker compose up -d postgres`, Postgres.app, "
            "or a Homebrew PostgreSQL service."
        ),
        ("linux", "postgresql"): (
            "Run `docker compose up -d postgres` or install PostgreSQL with your "
            "distribution package manager."
        ),
        ("windows", "postgresql"): (
            "Run `docker compose up -d postgres` with Docker Desktop or install "
            "PostgreSQL from https://www.postgresql.org/download/windows/."
        ),
    }
    return guidance.get(
        (system, dependency),
        f"Install {dependency} using the instructions for your operating system.",
    )


def _start_background_ollama() -> tuple[bool, str]:
    ollama = shutil.which("ollama")
    if ollama is None:
        return False, dependency_guidance("ollama")
    popen_kwargs: dict[str, object] = {
        "stdin": subprocess.DEVNULL,
        "stdout": subprocess.DEVNULL,
        "stderr": subprocess.DEVNULL,
    }
    if operating_system() == "windows":
        popen_kwargs["creationflags"] = (
            subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.DETACHED_PROCESS
        )
    else:
        popen_kwargs["start_new_session"] = True
    try:
        subprocess.Popen([ollama, "serve"], **popen_kwargs)  # noqa: S603
    except OSError as exc:
        return False, f"could not start `ollama serve`: {exc}"
    return True, "started `ollama serve` in the background"


def start_local_service(
    service: Literal["ollama", "postgresql"],
    *,
    postgres_service_name: str = "postgresql",
) -> tuple[bool, str]:
    if service == "ollama":
        if operating_system() == "macos" and _homebrew() is not None:
            ok, detail = start_homebrew_service("ollama")
            if ok:
                return ok, detail
        return _start_background_ollama()

    if operating_system() == "macos" and _homebrew() is not None:
        return start_homebrew_service(postgres_service_name)
    return False, dependency_guidance("postgresql")


def estimate_ollama_download_size(model: str) -> int | None:
    """Return a conservative byte estimate when a parameter count is in the tag."""
    match = OLLAMA_PARAMETER_COUNT.search(model)
    if match is None:
        return None
    parameters_billions = float(match.group(1))
    if parameters_billions <= 0 or parameters_billions > 1000:
        return None
    return max(4 * GIB, int((parameters_billions * 0.8 + 2) * GIB))


def _ollama_disk_probe_path() -> Path:
    configured = os.environ.get("OLLAMA_MODELS")
    candidate = (
        Path(configured).expanduser()
        if configured
        else Path.home() / ".ollama" / "models"
    ).resolve()
    while not candidate.exists() and candidate.parent != candidate:
        candidate = candidate.parent
    return candidate


def pull_ollama_model(
    model: str,
    *,
    expected_size_gb: float | None = None,
) -> tuple[bool, str]:
    ollama = shutil.which("ollama")
    if ollama is None:
        return False, "Ollama is not installed"
    expected_size = (
        int(expected_size_gb * GIB)
        if (
            expected_size_gb is not None
            and math.isfinite(expected_size_gb)
            and expected_size_gb > 0
        )
        else estimate_ollama_download_size(model)
    )
    if expected_size is None or expected_size <= 0:
        return (
            False,
            "cannot safely estimate this model download; rerun `trade models pull` "
            "with --expected-size-gb",
        )
    assessment = assess_model_download(
        model=model,
        expected_size_bytes=expected_size,
        snapshot=resource_snapshot(_ollama_disk_probe_path()),
    )
    if assessment.status == "block":
        return (
            False,
            f"download blocked before network transfer: {assessment.reason}; "
            f"{assessment.snapshot.disk_free_bytes / GIB:.1f} GiB free, "
            f"{assessment.estimated_runtime_bytes / GIB:.1f} GiB required",
        )
    result = subprocess.run(  # noqa: S603
        [ollama, "pull", model],
        check=False,
        text=True,
        timeout=1800,
    )
    return (
        result.returncode == 0,
        f"disk preflight passed; ollama pull exited with status {result.returncode}",
    )


def _ollama_ready(base_url: str) -> bool:
    try:
        with httpx.Client(timeout=1.0, trust_env=False) as client:
            response = client.get(f"{base_url.rstrip('/')}/api/tags")
            return response.is_success
    except httpx.HTTPError:
        return False


def _database_ready(engine: Engine) -> bool:
    try:
        with engine.connect():
            return True
    except Exception:
        return False


def ensure_local_services(settings: Settings, engine: Engine) -> tuple[str, ...]:
    if not settings.local_service_autostart:
        return ()

    messages: list[str] = []
    database_host = urlparse(settings.database_url.replace("+psycopg", "")).hostname
    if database_host in {"localhost", "127.0.0.1", "::1"} and not _database_ready(engine):
        ok, detail = start_local_service(
            "postgresql",
            postgres_service_name=settings.postgres_service_name,
        )
        messages.append(
            f"PostgreSQL {'start requested' if ok else 'could not start'}: {detail}"
        )

    if settings.model_provider == "ollama" and not _ollama_ready(settings.ollama_base_url):
        ok, detail = start_local_service("ollama")
        messages.append(f"Ollama {'start requested' if ok else 'could not start'}: {detail}")

    if messages:
        for _ in range(20):
            database_ok = database_host not in {"localhost", "127.0.0.1", "::1"} or _database_ready(
                engine
            )
            ollama_ok = settings.model_provider != "ollama" or _ollama_ready(
                settings.ollama_base_url
            )
            if database_ok and ollama_ok:
                break
            time.sleep(0.25)
    return tuple(messages)


def shell_path_hint(launcher: Path) -> str | None:
    directory = str(launcher.parent)
    path_entries = os.environ.get("PATH", "").split(os.pathsep)
    if directory in path_entries:
        return None
    if operating_system() == "windows":
        return (
            f"Add `{directory}` to your user PATH in Windows Environment Variables, "
            "then open a new terminal."
        )
    shell_file = "~/.zprofile" if sys.platform == "darwin" else "~/.profile"
    return f'Add `export PATH="$HOME/.local/bin:$PATH"` to {shell_file}, then reopen Terminal.'
